export interface Element {
    number: number;
    symbol: string;
    name: string;
    mass: number;
    category: string;
    group: number;
    period: number;
    color: string;
    electronegativity: number | null;
    atomic_radius: number | null;
    melting_point: number | null; // in K
    boiling_point: number | null; // in K
    density: number | null; // g/cm3
    summary: string;
}

export const CATEGORY_COLORS: Record<string, string> = {
    'nonmetal': '#4fd1c5',
    'noble gas': '#ed64a6',
    'alkali metal': '#f56565',
    'alkaline earth metal': '#ed8936',
    'metalloid': '#ecc94b',
    'post-transition metal': '#a0aec0',
    'transition metal': '#4299e1',
    'actinide': '#9f7aea',
    'lanthanide': '#805ad5',
};

export const ELEMENTS: Element[] = [
    { number: 1, symbol: 'H', name: 'Hydrogen', mass: 1.008, category: 'nonmetal', group: 1, period: 1, color: '#4fd1c5', electronegativity: 2.20, atomic_radius: 37, melting_point: 14.01, boiling_point: 20.28, density: 0.00008988, summary: 'The lightest and most abundant chemical substance in the universe.' },
    { number: 2, symbol: 'He', name: 'Helium', mass: 4.0026, category: 'noble gas', group: 18, period: 1, color: '#ed64a6', electronegativity: null, atomic_radius: 32, melting_point: 0.95, boiling_point: 4.22, density: 0.0001785, summary: 'A colorless, odorless, tasteless, non-toxic, inert, monatomic gas.' },
    { number: 3, symbol: 'Li', name: 'Lithium', mass: 6.94, category: 'alkali metal', group: 1, period: 2, color: '#f56565', electronegativity: 0.98, atomic_radius: 134, melting_point: 453.69, boiling_point: 1615, density: 0.534, summary: 'The lightest metal and the lightest solid element.' },
    { number: 4, symbol: 'Be', name: 'Beryllium', mass: 9.0122, category: 'alkaline earth metal', group: 2, period: 2, color: '#ed8936', electronegativity: 1.57, atomic_radius: 90, melting_point: 1560, boiling_point: 2742, density: 1.85, summary: 'A steel-gray, strong, lightweight and brittle alkaline earth metal.' },
    { number: 5, symbol: 'B', name: 'Boron', mass: 10.81, category: 'metalloid', group: 13, period: 2, color: '#ecc94b', electronegativity: 2.04, atomic_radius: 87, melting_point: 2349, boiling_point: 4200, density: 2.46, summary: 'A low-abundance metalloid element that is found in meteoroids.' },
    { number: 6, symbol: 'C', name: 'Carbon', mass: 12.011, category: 'nonmetal', group: 14, period: 2, color: '#4fd1c5', electronegativity: 2.55, atomic_radius: 77, melting_point: 3823, boiling_point: 4300, density: 2.267, summary: 'A nonmetallic tetravalent element that is the basis for all organic chemistry.' },
    { number: 7, symbol: 'N', name: 'Nitrogen', mass: 14.007, category: 'nonmetal', group: 15, period: 2, color: '#4fd1c5', electronegativity: 3.04, atomic_radius: 71, melting_point: 63.15, boiling_point: 77.36, density: 0.001251, summary: 'A common nonmetallic element that makes up 78% of Earth\'s atmosphere.' },
    { number: 8, symbol: 'O', name: 'Oxygen', mass: 15.999, category: 'nonmetal', group: 16, period: 2, color: '#4fd1c5', electronegativity: 3.44, atomic_radius: 66, melting_point: 54.36, boiling_point: 90.2, density: 0.001429, summary: 'A highly reactive nonmetal and oxidizing agent that is essential for life on Earth.' },
    { number: 9, symbol: 'F', name: 'Fluorine', mass: 18.998, category: 'nonmetal', group: 17, period: 2, color: '#4fd1c5', electronegativity: 3.98, atomic_radius: 57, melting_point: 53.53, boiling_point: 85.03, density: 0.001696, summary: 'The most electronegative and reactive of all elements, existing as a toxic pale yellow gas.' },
    { number: 10, symbol: 'Ne', name: 'Neon', mass: 20.18, category: 'noble gas', group: 18, period: 2, color: '#ed64a6', electronegativity: null, atomic_radius: 58, melting_point: 24.56, boiling_point: 27.07, density: 0.0009, summary: 'A colorless, odorless, inert monatomic gas that glows reddish-orange in a vacuum discharge tube.' },
    { number: 11, symbol: 'Na', name: 'Sodium', mass: 22.99, category: 'alkali metal', group: 1, period: 3, color: '#f56565', electronegativity: 0.93, atomic_radius: 166, melting_point: 370.87, boiling_point: 1156, density: 0.968, summary: 'A soft, silvery-white, highly reactive alkali metal.' },
    { number: 12, symbol: 'Mg', name: 'Magnesium', mass: 24.305, category: 'alkaline earth metal', group: 2, period: 3, color: '#ed8936', electronegativity: 1.31, atomic_radius: 141, melting_point: 923, boiling_point: 1363, density: 1.738, summary: 'A shiny gray solid which bears a close physical resemblance to the other five alkaline earth metals.' },
    { number: 13, symbol: 'Al', name: 'Aluminium', mass: 26.982, category: 'post-transition metal', group: 13, period: 3, color: '#a0aec0', electronegativity: 1.61, atomic_radius: 121, melting_point: 933.47, boiling_point: 2792, density: 2.7, summary: 'A silvery-white, soft, non-magnetic and ductile metal.' },
    { number: 14, symbol: 'Si', name: 'Silicon', mass: 28.085, category: 'metalloid', group: 14, period: 3, color: '#ecc94b', electronegativity: 1.90, atomic_radius: 111, melting_point: 1687, boiling_point: 3538, density: 2.3296, summary: 'A hard, brittle crystalline solid with a blue-grey metallic luster.' },
    { number: 15, symbol: 'P', name: 'Phosphorus', mass: 30.974, category: 'nonmetal', group: 15, period: 3, color: '#4fd1c5', electronegativity: 2.19, atomic_radius: 107, melting_point: 317.3, boiling_point: 553.6, density: 1.823, summary: 'A highly reactive nonmetal that exists in two major forms, white and red phosphorus.' },
    { number: 16, symbol: 'S', name: 'Sulfur', mass: 32.06, category: 'nonmetal', group: 16, period: 3, color: '#4fd1c5', electronegativity: 2.58, atomic_radius: 102, melting_point: 388.36, boiling_point: 717.8, density: 2.07, summary: 'An abundant, multivalent nonmetal, sulfur atoms form cyclic octatomic molecules.' },
    { number: 17, symbol: 'Cl', name: 'Chlorine', mass: 35.45, category: 'nonmetal', group: 17, period: 3, color: '#4fd1c5', electronegativity: 3.16, atomic_radius: 97, melting_point: 171.6, boiling_point: 239.11, density: 0.003214, summary: 'A pale yellow-green gas that is extremely reactive and a powerful oxidizing agent.' },
    { number: 18, symbol: 'Ar', name: 'Argon', mass: 39.948, category: 'noble gas', group: 18, period: 3, color: '#ed64a6', electronegativity: null, atomic_radius: 106, melting_point: 83.8, boiling_point: 87.3, density: 0.001784, summary: 'The third-most abundant gas in Earth\'s atmosphere, at 0.934%.' },
    { number: 19, symbol: 'K', name: 'Potassium', mass: 39.098, category: 'alkali metal', group: 1, period: 4, color: '#f56565', electronegativity: 0.82, atomic_radius: 203, melting_point: 336.5, boiling_point: 1032, density: 0.89, summary: 'A silvery-white metal that is soft enough to be cut with a knife.' },
    { number: 20, symbol: 'Ca', name: 'Calcium', mass: 40.078, category: 'alkaline earth metal', group: 2, period: 4, color: '#ed8936', electronegativity: 1.00, atomic_radius: 176, melting_point: 1115, boiling_point: 1757, density: 1.54, summary: 'An alkaline earth metal essential for living organisms, particularly in cell physiology.' },
    { number: 21, symbol: 'Sc', name: 'Scandium', mass: 44.956, category: 'transition metal', group: 3, period: 4, color: '#4299e1', electronegativity: 1.36, atomic_radius: 144, melting_point: 1814, boiling_point: 3109, density: 2.985, summary: 'A silvery-white metallic d-block element, historically classified as a rare-earth element.' },
    { number: 22, symbol: 'Ti', name: 'Titanium', mass: 47.867, category: 'transition metal', group: 4, period: 4, color: '#4299e1', electronegativity: 1.54, atomic_radius: 136, melting_point: 1941, boiling_point: 3560, density: 4.506, summary: 'A lustrous transition metal with a silver color, low density, and high strength.' },
    { number: 23, symbol: 'V', name: 'Vanadium', mass: 50.942, category: 'transition metal', group: 5, period: 4, color: '#4299e1', electronegativity: 1.63, atomic_radius: 125, melting_point: 2183, boiling_point: 3680, density: 6.0, summary: 'A hard, silvery-grey, malleable transition metal.' },
    { number: 24, symbol: 'Cr', name: 'Chromium', mass: 51.996, category: 'transition metal', group: 6, period: 4, color: '#4299e1', electronegativity: 1.66, atomic_radius: 127, melting_point: 2180, boiling_point: 2944, density: 7.19, summary: 'A steely-grey, lustrous, hard and brittle transition metal.' },
    { number: 25, symbol: 'Mn', name: 'Manganese', mass: 54.938, category: 'transition metal', group: 7, period: 4, color: '#4299e1', electronegativity: 1.55, atomic_radius: 139, melting_point: 1519, boiling_point: 2334, density: 7.21, summary: 'A transition metal with a multifaceted array of industrial alloy uses, particularly in stainless steels.' },
    { number: 26, symbol: 'Fe', name: 'Iron', mass: 55.845, category: 'transition metal', group: 8, period: 4, color: '#4299e1', electronegativity: 1.83, atomic_radius: 125, melting_point: 1811, boiling_point: 3134, density: 7.874, summary: 'A metal in the first transition series, making up much of Earth\'s outer and inner core.' },
    { number: 27, symbol: 'Co', name: 'Cobalt', mass: 58.933, category: 'transition metal', group: 9, period: 4, color: '#4299e1', electronegativity: 1.88, atomic_radius: 126, melting_point: 1768, boiling_point: 3200, density: 8.9, summary: 'A ferromagnetic metal found in the Earth\'s crust only in chemically combined form.' },
    { number: 28, symbol: 'Ni', name: 'Nickel', mass: 58.693, category: 'transition metal', group: 10, period: 4, color: '#4299e1', electronegativity: 1.91, atomic_radius: 121, melting_point: 1728, boiling_point: 3186, density: 8.908, summary: 'A silvery-white lustrous metal with a slight golden tinge.' },
    { number: 29, symbol: 'Cu', name: 'Copper', mass: 63.546, category: 'transition metal', group: 11, period: 4, color: '#4299e1', electronegativity: 1.90, atomic_radius: 138, melting_point: 1357.77, boiling_point: 2835, density: 8.96, summary: 'A soft, malleable, and ductile metal with very high thermal and electrical conductivity.' },
    { number: 30, symbol: 'Zn', name: 'Zinc', mass: 65.38, category: 'transition metal', group: 12, period: 4, color: '#4299e1', electronegativity: 1.65, atomic_radius: 131, melting_point: 692.68, boiling_point: 1180, density: 7.14, summary: 'A slightly brittle metal at room temperature, with a blue-silvery appearance when oxidation is removed.' },
    { number: 31, symbol: 'Ga', name: 'Gallium', mass: 69.723, category: 'post-transition metal', group: 13, period: 4, color: '#a0aec0', electronegativity: 1.81, atomic_radius: 126, melting_point: 302.91, boiling_point: 2673, density: 5.91, summary: 'A soft, silvery blue metal at standard temperature and pressure that melts in a person\'s hand.' },
    { number: 32, symbol: 'Ge', name: 'Germanium', mass: 72.63, category: 'metalloid', group: 14, period: 4, color: '#ecc94b', electronegativity: 2.01, atomic_radius: 122, melting_point: 1211.4, boiling_point: 3106, density: 5.323, summary: 'A lustrous, hard-brittle, grayish-white metalloid in the carbon group.' },
    { number: 33, symbol: 'As', name: 'Arsenic', mass: 74.922, category: 'metalloid', group: 15, period: 4, color: '#ecc94b', electronegativity: 2.18, atomic_radius: 119, melting_point: 1090, boiling_point: 887, density: 5.727, summary: 'A metalloid that occurs in many minerals, usually in combination with sulfur and metals.' },
    { number: 34, symbol: 'Se', name: 'Selenium', mass: 78.971, category: 'nonmetal', group: 16, period: 4, color: '#4fd1c5', electronegativity: 2.55, atomic_radius: 116, melting_point: 494, boiling_point: 958, density: 4.81, summary: 'A nonmetal with properties that are intermediate between the elements sulfur and tellurium.' },
    { number: 35, symbol: 'Br', name: 'Bromine', mass: 79.904, category: 'nonmetal', group: 17, period: 4, color: '#4fd1c5', electronegativity: 2.96, atomic_radius: 120, melting_point: 265.8, boiling_point: 332, density: 3.1028, summary: 'The only nonmetallic element that is a liquid under standard conditions.' },
    { number: 36, symbol: 'Kr', name: 'Krypton', mass: 83.798, category: 'noble gas', group: 18, period: 4, color: '#ed64a6', electronegativity: 3.00, atomic_radius: 110, melting_point: 115.79, boiling_point: 119.93, density: 0.003733, summary: 'A colorless, odorless, tasteless noble gas that occurs in trace amounts in the atmosphere.' },
    { number: 37, symbol: 'Rb', name: 'Rubidium', mass: 85.468, category: 'alkali metal', group: 1, period: 5, color: '#f56565', electronegativity: 0.82, atomic_radius: 211, melting_point: 312.46, boiling_point: 961, density: 1.53, summary: 'A soft, silvery-white, extremely reactive alkali metal.' },
    { number: 38, symbol: 'Sr', name: 'Strontium', mass: 87.62, category: 'alkaline earth metal', group: 2, period: 5, color: '#ed8936', electronegativity: 0.95, atomic_radius: 192, melting_point: 1050, boiling_point: 1655, density: 2.64, summary: 'A highly chemically reactive alkaline earth metal; the metal turns yellow when exposed to air.' },
    { number: 39, symbol: 'Y', name: 'Yttrium', mass: 88.906, category: 'transition metal', group: 3, period: 5, color: '#4299e1', electronegativity: 1.22, atomic_radius: 162, melting_point: 1799, boiling_point: 3609, density: 4.472, summary: 'A silvery-metallic transition metal chemically similar to the lanthanides.' },
    { number: 40, symbol: 'Zr', name: 'Zirconium', mass: 91.224, category: 'transition metal', group: 4, period: 5, color: '#4299e1', electronegativity: 1.33, atomic_radius: 148, melting_point: 2128, boiling_point: 4682, density: 6.52, summary: 'A lustrous, greyish-white, strong transition metal that resembles hafnium and, to a lesser extent, titanium.' },
    { number: 41, symbol: 'Nb', name: 'Niobium', mass: 92.906, category: 'transition metal', group: 5, period: 5, color: '#4299e1', electronegativity: 1.6, atomic_radius: 137, melting_point: 2750, boiling_point: 5017, density: 8.57, summary: 'A light grey, crystalline, and ductile transition metal.' },
    { number: 42, symbol: 'Mo', name: 'Molybdenum', mass: 95.95, category: 'transition metal', group: 6, period: 5, color: '#4299e1', electronegativity: 2.16, atomic_radius: 130, melting_point: 2896, boiling_point: 4912, density: 10.28, summary: 'A refractory transition metal that does not occur as a free metal on Earth.' },
    { number: 46, symbol: 'Pd', name: 'Palladium', mass: 106.42, category: 'transition metal', group: 10, period: 5, color: '#4299e1', electronegativity: 2.20, atomic_radius: 131, melting_point: 1828.05, boiling_point: 3236, density: 12.023, summary: 'A rare and lustrous silvery-white metal discovered in 1803.' },
    { number: 47, symbol: 'Ag', name: 'Silver', mass: 107.87, category: 'transition metal', group: 11, period: 5, color: '#4299e1', electronegativity: 1.93, atomic_radius: 153, melting_point: 1234.93, boiling_point: 2435, density: 10.49, summary: 'A transition metal with the highest electrical conductivity, thermal conductivity, and reflectivity of any metal.' },
    { number: 48, symbol: 'Cd', name: 'Cadmium', mass: 112.41, category: 'transition metal', group: 12, period: 5, color: '#4299e1', electronegativity: 1.69, atomic_radius: 148, melting_point: 594.22, boiling_point: 1040, density: 8.65, summary: 'A soft, maleable, silvery-white transition metal that is chemically similar to zinc and mercury.' },
    { number: 49, symbol: 'In', name: 'Indium', mass: 114.82, category: 'post-transition metal', group: 13, period: 5, color: '#a0aec0', electronegativity: 1.78, atomic_radius: 144, melting_point: 429.75, boiling_point: 2345, density: 7.31, summary: 'A post-transition metal that makes up 0.21 parts per million of the Earth\'s crust.' },
    { number: 50, symbol: 'Sn', name: 'Tin', mass: 118.71, category: 'post-transition metal', group: 14, period: 5, color: '#a0aec0', electronegativity: 1.96, atomic_radius: 141, melting_point: 505.08, boiling_point: 2875, density: 7.31, summary: 'A silvery, malleable post-transition metal that is not easily oxidized in air.' },
    { number: 51, symbol: 'Sb', name: 'Antimony', mass: 121.76, category: 'metalloid', group: 15, period: 5, color: '#ecc94b', electronegativity: 2.05, atomic_radius: 138, melting_point: 903.78, boiling_point: 1860, density: 6.697, summary: 'A lustrous gray metalloid, it is found in nature mainly as the sulfide mineral stibnite.' },
    { number: 52, symbol: 'Te', name: 'Tellurium', mass: 127.6, category: 'metalloid', group: 16, period: 5, color: '#ecc94b', electronegativity: 2.1, atomic_radius: 135, melting_point: 722.66, boiling_point: 1261, density: 6.24, summary: 'A mildly toxic, rare, silver-white metalloid that is chemically related to selenium and sulfur.' },
    { number: 53, symbol: 'I', name: 'Iodine', mass: 126.9, category: 'nonmetal', group: 17, period: 5, color: '#4fd1c5', electronegativity: 2.66, atomic_radius: 133, melting_point: 386.85, boiling_point: 457.4, density: 4.933, summary: 'A lustrous, purple-black nonmetal that is the heaviest of the stable halogens.' },
    { number: 54, symbol: 'Xe', name: 'Xenon', mass: 131.29, category: 'noble gas', group: 18, period: 5, color: '#ed64a6', electronegativity: 2.6, atomic_radius: 130, melting_point: 161.4, boiling_point: 165.03, density: 0.005887, summary: 'A colorless, dense, odorless noble gas found in Earth\'s atmosphere in trace amounts.' },
    { number: 55, symbol: 'Cs', name: 'Caesium', mass: 132.91, category: 'alkali metal', group: 1, period: 6, color: '#f56565', electronegativity: 0.79, atomic_radius: 265, melting_point: 301.59, boiling_point: 944, density: 1.93, summary: 'An alkali metal with physical and chemical properties similar to those of rubidium and potassium.' },
    { number: 56, symbol: 'Ba', name: 'Barium', mass: 137.33, category: 'alkaline earth metal', group: 2, period: 6, color: '#ed8936', electronegativity: 0.89, atomic_radius: 222, melting_point: 1000, boiling_point: 2118, density: 3.51, summary: 'A soft, silvery alkaline earth metal.' },
    { number: 74, symbol: 'W', name: 'Tungsten', mass: 183.84, category: 'transition metal', group: 6, period: 6, color: '#4299e1', electronegativity: 2.36, atomic_radius: 139, melting_point: 3695, boiling_point: 5828, density: 19.25, summary: 'A rare metal found naturally on Earth almost exclusively as compounds with other elements.' },
    { number: 78, symbol: 'Pt', name: 'Platinum', mass: 195.08, category: 'transition metal', group: 10, period: 6, color: '#4299e1', electronegativity: 2.28, atomic_radius: 139, melting_point: 2041.4, boiling_point: 4098, density: 21.45, summary: 'A dense, malleable, ductile, highly unreactive, precious, silver-white transition metal.' },
    { number: 79, symbol: 'Au', name: 'Gold', mass: 196.97, category: 'transition metal', group: 11, period: 6, color: '#4299e1', electronegativity: 2.4, atomic_radius: 144, melting_point: 1337.33, boiling_point: 3129, density: 19.3, summary: 'A bright, slightly reddish yellow, dense, soft, malleable, and ductile metal.' },
    { number: 80, symbol: 'Hg', name: 'Mercury', mass: 200.59, category: 'transition metal', group: 12, period: 6, color: '#4299e1', electronegativity: 2.00, atomic_radius: 151, melting_point: 234.32, boiling_point: 629.88, density: 13.534, summary: 'A heavy, silvery d-block element, mercury is the only metallic element that is liquid at standard conditions.' },
    { number: 82, symbol: 'Pb', name: 'Lead', mass: 207.2, category: 'post-transition metal', group: 14, period: 6, color: '#a0aec0', electronegativity: 2.33, atomic_radius: 175, melting_point: 600.61, boiling_point: 2022, density: 11.34, summary: 'A heavy metal that is denser than most common materials.' },
    { number: 83, symbol: 'Bi', name: 'Bismuth', mass: 208.98, category: 'post-transition metal', group: 15, period: 6, color: '#a0aec0', electronegativity: 2.02, atomic_radius: 156, melting_point: 544.7, boiling_point: 1837, density: 9.78, summary: 'A brittle metal with a white, silver-pink hue.' },
    { number: 84, symbol: 'Po', name: 'Polonium', mass: 209, category: 'post-transition metal', group: 16, period: 6, color: '#a0aec0', electronegativity: 2.0, atomic_radius: 167, melting_point: 527, boiling_point: 1235, density: 9.196, summary: 'A rare and highly radioactive metal with no stable isotopes.' },
    { number: 85, symbol: 'At', name: 'Astatine', mass: 210, category: 'metalloid', group: 17, period: 6, color: '#ecc94b', electronegativity: 2.2, atomic_radius: 127, melting_point: 575, boiling_point: 610, density: 7, summary: 'A highly radioactive chemical element with symbol At and atomic number 85.' },
    { number: 86, symbol: 'Rn', name: 'Radon', mass: 222, category: 'noble gas', group: 18, period: 6, color: '#ed64a6', electronegativity: 2.2, atomic_radius: 120, melting_point: 202, boiling_point: 211.3, density: 0.00973, summary: 'A radioactive, colorless, odorless, tasteless noble gas.' },
    { number: 87, symbol: 'Fr', name: 'Francium', mass: 223, category: 'alkali metal', group: 1, period: 7, color: '#f56565', electronegativity: 0.7, atomic_radius: null, melting_point: 300, boiling_point: 950, density: 1.87, summary: 'An alkali metal that is highly radioactive and relatively rare.' },
    { number: 88, symbol: 'Ra', name: 'Radium', mass: 226, category: 'alkaline earth metal', group: 2, period: 7, color: '#ed8936', electronegativity: 0.9, atomic_radius: null, melting_point: 973, boiling_point: 2010, density: 5.5, summary: 'A pure-white alkaline earth metal that blackens on exposure to air.' },
    { number: 92, symbol: 'U', name: 'Uranium', mass: 238.03, category: 'actinide', group: 3, period: 7, color: '#9f7aea', electronegativity: 1.38, atomic_radius: 138, melting_point: 1405.3, boiling_point: 4404, density: 18.95, summary: 'A silvery-grey metal in the actinide series of the periodic table.' },
    { number: 94, symbol: 'Pu', name: 'Plutonium', mass: 244, category: 'actinide', group: 3, period: 7, color: '#9f7aea', electronegativity: 1.28, atomic_radius: 159, melting_point: 912.5, boiling_point: 3501, density: 19.816, summary: 'A transuranic radioactive chemical element with symbol Pu and atomic number 94.' },
];

export const getElementStateAtTemp = (element: Element, tempK: number): 'solid' | 'liquid' | 'gas' | 'synthetic' => {
    if (element.melting_point === null && element.boiling_point === null) {
        return 'synthetic';
    }
    const mp = element.melting_point ?? 0;
    const bp = element.boiling_point ?? 99999;
    
    if (tempK < mp) return 'solid';
    if (tempK < bp) return 'liquid';
    return 'gas';
};
